### ISSUE TITLE
Error in running dev host

### ISSUE THREAD

**Issue by mohmedkasim** [mohmedkasim/react-vite-website#1]
running: npm run dev cause a problem after git repository update
```
Error: listen EACCES: permission denied 127.0.0.1:4200
    at Server.setupListenHandle [as _listen2] (net.js:1253:19)
    at listenInCluster (net.js:1318:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1451:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
```

**Comment by mohmedkasim** [comment]
run command
```
net stop winnat
net start winnat
```
and try again.
